version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: font-awesome-sass
    versions:
    - "> 4.7.0"
  - dependency-name: middleman-blog
    versions:
    - "> 4.0.1"
  - dependency-name: html-proofer
    versions:
    - 3.18.5
    - 3.18.6
    - 3.18.8
    - 3.19.0
  - dependency-name: fog-aws
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: mime-types-data
    versions:
    - 3.2020.1104
    - 3.2021.0212
  - dependency-name: fastimage
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: backports
    versions:
    - 3.20.2
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: ffi
    versions:
    - 1.14.2
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
